### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [greymd/docker-zsh-completion#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by greymd** [comment]
Oh, I see..
Added https://github.com/greymd/docker-zsh-completion/blob/master/LICENSE

thx!

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/828, thanks!
